# Generated by Django 3.2.9 on 2021-11-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_systen',
            new_name='fav_system',
        ),
    ]
