# Generated by Django 3.2.9 on 2021-12-14 15:49

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='valid_to',
            field=models.DateTimeField(default=datetime.now, blank=True),
            preserve_default=False,
        ),
    ]
